### ISSUE TITLE
Add additional wildcard test "Wildcard applies to the domain(s)"

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/cab-csr-validator#2]
Beside the “18. Wildcard present” test add 19. “Wildcard applies to the domain(s)”.
If no Wildcards are detected in 18. this test will be “Passed”.

The * must apply to a valid domain detected in the list and not to a public suffix as in https://publicsuffix.org/list/
Example:
- *.cartel.ch is fine, *.ch is not ok
- *.bp.co.uk is fine, *.co.uk is not ok (co.uk is a

Refer to 3.2.2.6 of https://cabforum.org/wp-content/uploads/Baseline_Requirements_V1_3_1.pdf

**Comment by michellotto** [comment]
Implemented, can you test it..

**Comment by FreddyKaiser** [comment]
Tested and ok
