### ISSUE TITLE
Cleanups 

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/cab-csr-validator#3]
On the first page
* change the color of "Chose file" and "Clear form" to something different as the "Launch test" (Gray?)

On the details
* all error results are displaying "No , your certificate request does not meet the CAB OV requirements." where after the No there is one space before the , that should be removed.

**Comment by michellotto** [comment]
Implemented, please, test it..

**Comment by FreddyKaiser** [comment]
The "Validate CSR" should remain "Blue" as it was.

**Comment by michellotto** [comment]
Changed, please, test it.
