### ISSUE TITLE
S seems be detected and displayed as ST

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/cab-csr-validator#4]
When trying to create certificates with /S for State and /ST for Street (unless I'm wrong) it will not create the /S one and define /ST for State

**Comment by FreddyKaiser** [comment]
Infos out of http://php.net/manual/en/openssl.installation.php PHP will search for the openssl.cnf using the following logic:
* the OPENSSL_CONF environmental variable, if set, will be used as the path (including filename) of the configuration file.
* the SSLEAY_CONF environmental variable, if set, will be used as the path (including filename) of the configuration file.
* The file openssl.cnf will be assumed to be found in the default certificate area

**Comment by FreddyKaiser** [comment]
```
    // Native
    print_r('>>> ' . $csrItem . ' <<<' . PHP_EOL);
    $csr_subject = openssl_csr_get_subject($csr, false);
    print_r($csr_subject);
    $csr_subject = openssl_csr_get_subject($csr, true);
    print_r($csr_subject);}
```

```
>>> _error_/b-hmssp.prod.mobileid_csr.txt <<<
Array
(
    [countryName] => CH
    [stateOrProvinceName] => ZH
    [localityName] => Zuerich
    [organizationName] => Swisscom (Schweiz) AG
    [organizationalUnitName] => Array
        (
            [0] => Security Operation and Engineering
            [1] => MobileID Production
        )

    [emailAddress] => s3.eod@swisscom.com
    [commonName] => b-hmssp.prod.mobileid
)
Array
(
    [C] => CH
    [ST] => ZH
    [L] => Zuerich
    [O] => Swisscom (Schweiz) AG
    [OU] => Array
        (
            [0] => Security Operation and Engineering
            [1] => MobileID Production
        )

    [emailAddress] => s3.eod@swisscom.com
    [CN] => b-hmssp.prod.mobileid
)
```

**Comment by FreddyKaiser** [comment]
Ok in PHP the /ST is not Street but stateOrProvinceName.

Please change the ST to State and remove the current S as State.
Be careful as the test "8. Locality (L) or State (S) mandatory" must also be changed to Street (ST) mandator.

**Comment by michellotto** [comment]
Corrected. Please, test it.

**Comment by FreddyKaiser** [comment]
Tested and ok
