### ISSUE TITLE
Display the rest of the subject

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/cab-csr-validator#5]
It seems that not all elements of the Subject are parsed and displayed.

Here an example of a CSR having a "Street":

```
-----BEGIN CERTIFICATE REQUEST-----
MIID3zCCAscCAQAwgaExCzAJBgNVBAYTAkNIMRYwFAYDVQQIEw1LYW50b24gWnVy
aWNoMQ8wDQYDVQQHEwZadXJpY2gxETAPBgNVBAoTCFN3aXNzY29tMR0wGwYDVQQL
ExRFbnRlcnByaXNlIEN1c3RvbWVyczEeMBwGA1UEAxMVd3d3LnN3aXNzdHJ1c3Ry
b29tLmNoMRcwFQYDVQQJEw5NdWVsbGVyc3RyYXNzZTCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAOW375G6OrV4to8lRrLxJPanxtycqx43S6nb3YdNA0v4
ztQNnA3o+6rqyRnyrxjCGoMJS4V/o2d1xX8QLFI+TEJ3K3yxzQGSd9+YQYtDsGiQ
Ie+cdGYXwaXW02KJGwqAlgAARLFZdONH7DwWMkTjxr5fpm22aqilg75zBkYjoo10
CGyai2d8gRdryVN58GDCAn2cgxet+w386B/W4eXExXASGCKMIoi5HwyyUPSJ2cxC
ESGONv9lCs09gx+auZBpdJAktUHVuO1AdyiblsUUt2HviZj19HOJdy8j8rhR4y/n
zH8gMklBT2yW/ptGm/cW4XuRnGtGiW23E83ZagM1O5ECAwEAAaCB9zCB9AYJKoZI
hvcNAQkOMYHmMIHjMAsGA1UdDwQEAwIEMDATBgNVHSUEDDAKBggrBgEFBQcDATCB
vgYDVR0RBIG2MIGzghV3d3cuc3dpc3N0cnVzdHJvb20uY2iCF3d3dy1jLnN3aXNz
dHJ1c3Ryb29tLmNoghFzd2lzc3RydXN0cm9vbS5jaIINKi5zd2lzc2NvbS5jaIIU
d3d3LnN3aXNzZGlnaWNlcnQuY2iCFW9jc3Auc3dpc3NkaWdpY2VydC5jaIIUYWlh
LnN3aXNzZGlnaWNlcnQuY2iCFHRzcy5zd2lzc2RpZ2ljZXJ0LmNoggCHBMLRLWUw
DQYJKoZIhvcNAQEFBQADggEBALE8W1fqNLNWH/I4iYTFNeYN59y+jwp2WGiGrHsE
x9eT3xLlDEdm0fIMhfn9zThUZK2bLjiZ8smwjYjEssycVbhBDA2VGlRE3IBj7pNV
Wp6HTTLAwuWFeaT6OX4ev7k/A5nugmR45R3BorIY7avUmF8cjbvcjzN6QmSRKfjY
nNQxBeWM7K9K3Ysh9nLaoSxx461WP5meGnapKO88zHMN5SnH/PPR/ahshg4pwvB5
rS5I47YqHWa8LhgyQJfZt/2TIIjmX1QmySUjO92gYp4eBIUMPwAA1eJAIJkHUZCa
dXQV/l12EmvzVHjRL9WW52Oqs+Rk/vkzNqyzyGnsNrzT760=
-----END CERTIFICATE REQUEST-----

```
By using https://certlogik.com/decoder/ you will see it

**Comment by michellotto** [comment]
Could you detail your request please, thanks.

**Comment by FreddyKaiser** [comment]
Here the details

**Comment by michellotto** [comment]
Issue should be solved, please, test it.

**Comment by FreddyKaiser** [comment]
You should also handle the default in the `case default:` when in the Subject an undefined/unhandled field is present. In this case add all the rest to 'Other elements in the DN': "xyz"
where "xyz" .= strtolower($key) ":"$value;

See: https://github.com/SCS-CBU-CED-IAM/cab-csr-validator/blob/92338a73406eacb8d0457909957fe38611c4a28e/helpers/validator-helper.php#L412

**Comment by michellotto** [comment]
Implemented, please, test it or give me a CSR where I can test this feature.

**Comment by FreddyKaiser** [comment]
Ok, small change. 

Like for SANs, instead of "Others" make it "Unknown DN entry (%s)" where %s is the strtolover($key) element

Here a sample CSR with following Subject: C=DE, ST=Hessen, L=Keller/postalCode=424242/street=Crater 1621, O=apfelboymschule, OU=IT Department, CN=example.com/emailAddress=webmaster@example.com/businessCategory=Government/jurisdictionL=Sion/jurisdictionST=VS/jurisdictionC=Switzerland

```
-----BEGIN CERTIFICATE REQUEST-----
MIIDqTCCApECAQAwggEjMQswCQYDVQQGDAJERTEPMA0GA1UECAwGSGVzc2VuMQ8w
DQYDVQQHDAZLZWxsZXIxDzANBgNVBBEMBjQyNDI0MjEUMBIGA1UECQwLQ3JhdGVy
IDE2MjExGDAWBgNVBAoMD2FwZmVsYm95bXNjaHVsZTEWMBQGA1UECwwNSVQgRGVw
YXJ0bWVudDEUMBIGA1UEAwwLZXhhbXBsZS5jb20xJDAiBgkqhkiG9w0BCQEWFXdl
Ym1hc3RlckBleGFtcGxlLmNvbTETMBEGA1UEDwwKR292ZXJubWVudDEVMBMGCysG
AQQBgjc8AgEBDARTaW9uMRMwEQYLKwYBBAGCNzwCAQIMAlZTMRwwGgYLKwYBBAGC
NzwCAQMMC1N3aXR6ZXJsYW5kMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEApC2545iGqoSdIgkBMZo3fO2Orj6rvbwS3cSvwq8Jm0OvtTLa5U+DFiCgCDWH
GRn08UiRXxO33efAIsMB8P45y5UjNf4mfDkfBDxpulp4FkiyZo4fBk2Gm274TO31
eiS0w/3i+q+pjAI5qYp+T7xSsSvKbMNoabA/3Rf/FQwiM3X65dE7Izgbz/OpkRZw
r5L2LQ+BvFHrh+uFdySyAEwH5x0/RQ1ZS9D/UbsN1cCXZtleGrtUz/dTOKbTwIxB
g6MmFeEAXnYrTKwwnwJ8njg4GEyx83FP580JVJBqj4KGHZUZioWOiAqZ/A3ncPd9
pAr5ffbvRmUKu16eRrLbjMp+gQIDAQABoD8wPQYJKoZIhvcNAQkOMTAwLjAsBgNV
HREEJTAjgg93d3cuZXhhbXBsZS5jb22CEHd3dzIuZXhhbXBsZS5jb20wDQYJKoZI
hvcNAQELBQADggEBABcRTeXGiuG1YxfN17igQqDlQGlrUl1lSOXuIKcshGUdblij
SzzVvZK/Lg/+58Hl/ZXgXsLvLNhS5qvL49obx9CfyKGQ8UZgWwla3TXHh3uKVzPe
+A9ej3XMAsmxm0ICVTS4baER9U8oVzAqtfYI4ccL2zYH4vI+s79d5hDCbxpoHS0f
LgLP5C9Jf4/FKy4ESrDYDRBU+H6JS+bRro18VASUFjmYkSLGtGvPYQzAabdzQl3I
/FL5MJSXK98yuEr2YceVKw2pUCW2WtgfWF2nYeoAjRq5XNovTO2+qMQ92tHn2zVP
GQa0FL7n2VNpFXs/iXTOinqbiD5snoyPhLpm6zU=
-----END CERTIFICATE REQUEST-----

```

**Comment by FreddyKaiser** [comment]
Ok, small changes. 

a) Like for SANs, instead of "Others" make it "Unknown DN entry (%s)" where %s is the strtolover($key) element
b) Ensure that undef:Array are not appearing (see results with this CSR)
c) CSR Details (Link at the bottom) is not displaying the entire Subject

Here a sample CSR with following Subject: C=DE, ST=Hessen, L=Keller/postalCode=424242/street=Crater 1621, O=apfelboymschule, OU=IT Department, CN=example.com/emailAddress=webmaster@example.com/businessCategory=Government/jurisdictionL=Sion/jurisdictionST=VS/jurisdictionC=Switzerland

```
-----BEGIN CERTIFICATE REQUEST-----
MIIDqTCCApECAQAwggEjMQswCQYDVQQGDAJERTEPMA0GA1UECAwGSGVzc2VuMQ8w
DQYDVQQHDAZLZWxsZXIxDzANBgNVBBEMBjQyNDI0MjEUMBIGA1UECQwLQ3JhdGVy
IDE2MjExGDAWBgNVBAoMD2FwZmVsYm95bXNjaHVsZTEWMBQGA1UECwwNSVQgRGVw
YXJ0bWVudDEUMBIGA1UEAwwLZXhhbXBsZS5jb20xJDAiBgkqhkiG9w0BCQEWFXdl
Ym1hc3RlckBleGFtcGxlLmNvbTETMBEGA1UEDwwKR292ZXJubWVudDEVMBMGCysG
AQQBgjc8AgEBDARTaW9uMRMwEQYLKwYBBAGCNzwCAQIMAlZTMRwwGgYLKwYBBAGC
NzwCAQMMC1N3aXR6ZXJsYW5kMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEApC2545iGqoSdIgkBMZo3fO2Orj6rvbwS3cSvwq8Jm0OvtTLa5U+DFiCgCDWH
GRn08UiRXxO33efAIsMB8P45y5UjNf4mfDkfBDxpulp4FkiyZo4fBk2Gm274TO31
eiS0w/3i+q+pjAI5qYp+T7xSsSvKbMNoabA/3Rf/FQwiM3X65dE7Izgbz/OpkRZw
r5L2LQ+BvFHrh+uFdySyAEwH5x0/RQ1ZS9D/UbsN1cCXZtleGrtUz/dTOKbTwIxB
g6MmFeEAXnYrTKwwnwJ8njg4GEyx83FP580JVJBqj4KGHZUZioWOiAqZ/A3ncPd9
pAr5ffbvRmUKu16eRrLbjMp+gQIDAQABoD8wPQYJKoZIhvcNAQkOMTAwLjAsBgNV
HREEJTAjgg93d3cuZXhhbXBsZS5jb22CEHd3dzIuZXhhbXBsZS5jb20wDQYJKoZI
hvcNAQELBQADggEBABcRTeXGiuG1YxfN17igQqDlQGlrUl1lSOXuIKcshGUdblij
SzzVvZK/Lg/+58Hl/ZXgXsLvLNhS5qvL49obx9CfyKGQ8UZgWwla3TXHh3uKVzPe
+A9ej3XMAsmxm0ICVTS4baER9U8oVzAqtfYI4ccL2zYH4vI+s79d5hDCbxpoHS0f
LgLP5C9Jf4/FKy4ESrDYDRBU+H6JS+bRro18VASUFjmYkSLGtGvPYQzAabdzQl3I
/FL5MJSXK98yuEr2YceVKw2pUCW2WtgfWF2nYeoAjRq5XNovTO2+qMQ92tHn2zVP
GQa0FL7n2VNpFXs/iXTOinqbiD5snoyPhLpm6zU=
-----END CERTIFICATE REQUEST-----

```

**Comment by michellotto** [comment]
Ok, implemented, please, test it.

**Comment by FreddyKaiser** [comment]
Seems not displaying all the elements in the Subject of this CSR, the numeric OIDs are missing:
`Subject: C=DE, ST=Hessen, L=Keller/postalCode=424242/street=Crater 1621, O=apfelboymschule, OU=IT Department, CN=example.com/emailAddress=webmaster@example.com/businessCategory=Government/1.3.6.1.4.1.311.60.2.1.1=Sion/1.3.6.1.4.1.311.60.2.1.2=VS/1.3.6.1.4.1.311.60.2.1.3=Switzerland
`

Also the display of the CSR is leaking over the window:
![screen shot 2016-02-18 at 11 14 45](https://cloud.githubusercontent.com/assets/4628116/13140248/2dee5b58-d631-11e5-8c78-98bba47c94d9.png)

**Comment by michellotto** [comment]
This kind of element are set to an indice named "UNDEF". See the result of the php function openssl_csr_get_subject()
http://php.net/manual/fr/function.openssl-csr-get-subject.php
---
array(11) {
  'C' =>
  string(2) "DE"
  'ST' =>
  string(6) "Hessen"
  'L' =>
  string(6) "Keller"
  'postalCode' =>
  string(6) "424242"
  'street' =>
  string(11) "Crater 1621"
  'O' =>
  string(15) "apfelboymschule"
  'OU' =>
  string(13) "IT Department"
  'CN' =>
  string(11) "example.com"
  'emailAddress' =>
  string(21) "webmaster@example.com"
  'businessCategory' =>
  string(10) "Government"
  'UNDEF' =>
  array(3) {
    [0] =>
    string(4) "Sion"
    [1] =>
    string(2) "VS"
    [2] =>
    string(11) "Switzerland"
  }
}
---

Display of CSR issue should be solved with my last commit.

**Comment by FreddyKaiser** [comment]
Can you then Put each element of the UNDEF Array into one line: UNDEF and the value in the column ?

**Comment by FreddyKaiser** [comment]
Can you then Put each element of the UNDEF Array into one line: UNDEF and the value in the column ?
Alternatie would to parse the subject out of the openssl parsed element instead of using the openssl_csr_get_subject function

**Comment by michellotto** [comment]
Ok, done, please, test it.

**Comment by FreddyKaiser** [comment]
It's only displaying one element of the array "UNDEF"

**Comment by michellotto** [comment]
ok, corrected.

**Comment by FreddyKaiser** [comment]
Ah and could you add a APP_REQUEST_SUBJECT_UNDEF="Undefined OID" and use this instead of "UNDEF" ($key)

**Comment by michellotto** [comment]
ok, done.

**Comment by FreddyKaiser** [comment]
Perfect
